# 公共配置文件
# @author ""程序员马建</a>
# @from <a href="">自我开发项目</a>
spring:
  application:
    name: majian-ojSystem-judge-service
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/majianoj
    username: root
    password: 123456
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 1
    host: 192.168.242.136
    port: 6379
    timeout: 5000
    password: majian123
  rabbitmq:
    host: 192.168.242.136
    port: 5672
    password: mypass
    username: myuser
    listener:
      simple:
        retry:
          enabled: true # 启用重试
          max-attempts: 3 # 最大尝试次数
          initial-interval: 1000 # 初始重试间隔（毫秒）
          max-interval: 10000 # 最大重试间隔（毫秒）
          multiplier: 2
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  #  elasticsearch:
  #    uris: http://localhost:9200
  #    username: root
  #    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.242.136:8848
server:
  address: 0.0.0.0
  servlet:
    context-path: /api/judge
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
  port: 8121
codeSendBox:
  type: remote
knife4j:
  enable: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
